name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      CDP_API_KEY_NAME: ${{ secrets.CDP_API_KEY_NAME }}
      CDP_API_KEY_PRIVATE_KEY: ${{ secrets.CDP_API_KEY_PRIVATE_KEY }}
      NETWORK_ID: base-mainnet

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run linting
      run: npm run lint
    
    - name: Run format check
      run: npm run format-check
    
    - name: Create env file
      run: |
        echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env
        echo "CDP_API_KEY_NAME=${{ secrets.CDP_API_KEY_NAME }}" >> .env
        echo "CDP_API_KEY_PRIVATE_KEY=${{ secrets.CDP_API_KEY_PRIVATE_KEY }}" >> .env
        echo "NETWORK_ID=base-mainnet" >> .env
    
    - name: Build Docker image
      run: docker build -t chatbot-api .
    
    - name: Test API
      run: |
        docker run -d -p 3000:3000 --env-file .env --name chatbot-test chatbot-api
        sleep 10
        curl -f -X POST http://localhost:3000/chat -H "Content-Type: application/json" -d '{"text":"test"}'
        docker stop chatbot-test
