name: Build and Push Node.js Docker Image (GCP)

on:
  push:
    tags: ["*"]

env:
  GAR_REPO: us-west1-docker.pkg.dev/shared-resources-alt/agentkit-ts/agentkit-ts

jobs:
  build_and_push:
    name: Build and Push Docker Image to GAR
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Extract App Name & Tag from Git Tag
      - name: Extract App Name and Tag
        run: |
          tag=${GITHUB_REF#refs/*/}
          app=$(echo $tag | rev | cut -d- -f2- | rev)
          echo "TAG=$tag" >> $GITHUB_ENV
          echo "APP=$app" >> $GITHUB_ENV

      # Step 3: Authenticate to Google Cloud
      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      # Step 4: Set up Cloud SDK
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          project_id: shared-resources-alt

      # Step 5: Configure Docker for GAR
      - name: Configure Docker for GAR
        run: gcloud auth configure-docker us-west1-docker.pkg.dev

      # Step 6: Extract Docker Metadata
      - name: Extract Metadata (Tags, Labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.GAR_REPO }}
          tags: |
            type=raw,value=${{ env.TAG }}
            type=raw,value=latest

      # Step 7: Build and Push Docker Image to GAR
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.GAR_REPO }}:${{ env.TAG }}
            ${{ env.GAR_REPO }}:latest
